version: '3'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_myapp
      - MARIADB_DATABASE=bitnami_myapp
  laravel:
    image: docker.io/bitnami/laravel:10
    ports:
      - '8000:8000'
      - '6006:6006'
    environment:
      - LARAVEL_APP_NAME="Laravel Storybook"
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=bn_myapp
      - DB_DATABASE=bitnami_myapp
    volumes:
      # TODO: Expectation is to remove the main folder from here.
      - './laravel:/app'
      # - './packages:/packages'
      # - './stories:/resources/views/stories'
      # - './tests:/tests'
    depends_on:
      - mariadb
